fix: cosign verify
It seems like cosign tries to verify all .sig files on the registry for
that digest, one of which is generated by cosign sign with a static key
and one is generated by actions/attest using an OIDC.

This exactly broke, which is what we have been using for the longest
time:

```
cosign verify --key cosign.pub ghcr.io/ublue-os/aurora:latest

Error: no matching attestations: expected key signature, not certificate
error during command execution: no matching attestations: expected key
signature, not certificate
```

And this currently works to verify the image, although it is of course
not the same thing as singing with the ublue cosign key.

This will not work going forward after this commit:

```
cosign verify \
  --certificate-oidc-issuer https://token.actions.githubusercontent.com \
  --certificate-identity-regexp="github.com/ublue-os/aurora/.github/workflows/*" \
  ghcr.io/ublue-os/aurora:latest
```

Signed-off-by: renner <renner0@posteo.de>